# Generated by Django 5.2.6 on 2025-10-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SEOSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Meta Title"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Meta Description"
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Meta Keywords"
                    ),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="OG Title"
                    ),
                ),
                (
                    "og_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="OG Description"
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="settings/",
                        verbose_name="OG Image",
                    ),
                ),
                (
                    "twitter_card",
                    models.CharField(
                        default="summary_large_image",
                        max_length=20,
                        verbose_name="Twitter Card Type",
                    ),
                ),
                (
                    "twitter_site",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Twitter Site"
                    ),
                ),
                (
                    "twitter_creator",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Twitter Creator"
                    ),
                ),
                (
                    "google_analytics_id",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Google Analytics ID"
                    ),
                ),
                (
                    "google_tag_manager_id",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Google Tag Manager ID"
                    ),
                ),
                (
                    "yandex_metrica_id",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Яндекс.Метрика ID"
                    ),
                ),
                (
                    "facebook_pixel_id",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Facebook Pixel ID"
                    ),
                ),
                (
                    "vk_pixel_id",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="VK Pixel ID"
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Название организации"
                    ),
                ),
                (
                    "organization_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="settings/",
                        verbose_name="Логотип организации",
                    ),
                ),
                (
                    "organization_description",
                    models.TextField(blank=True, verbose_name="Описание организации"),
                ),
                (
                    "robots_txt",
                    models.TextField(blank=True, verbose_name="Содержимое robots.txt"),
                ),
                (
                    "sitemap_enabled",
                    models.BooleanField(default=True, verbose_name="Включить sitemap"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
            ],
            options={
                "verbose_name": "SEO и аналитика",
                "verbose_name_plural": "SEO и аналитика",
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site_name",
                    models.CharField(
                        default="TubeCMS", max_length=100, verbose_name="Название сайта"
                    ),
                ),
                (
                    "site_description",
                    models.TextField(blank=True, verbose_name="Описание сайта"),
                ),
                (
                    "site_keywords",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Ключевые слова"
                    ),
                ),
                (
                    "site_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="settings/",
                        verbose_name="Логотип сайта",
                    ),
                ),
                (
                    "site_favicon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="settings/",
                        verbose_name="Фавикон",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Контактный email"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Контактный телефон"
                    ),
                ),
                ("contact_address", models.TextField(blank=True, verbose_name="Адрес")),
                ("social_vk", models.URLField(blank=True, verbose_name="VK")),
                (
                    "social_telegram",
                    models.URLField(blank=True, verbose_name="Telegram"),
                ),
                ("social_youtube", models.URLField(blank=True, verbose_name="YouTube")),
                ("social_twitter", models.URLField(blank=True, verbose_name="Twitter")),
                (
                    "social_instagram",
                    models.URLField(blank=True, verbose_name="Instagram"),
                ),
                (
                    "max_video_size",
                    models.PositiveIntegerField(
                        default=500, verbose_name="Максимальный размер видео (MB)"
                    ),
                ),
                (
                    "max_video_duration",
                    models.PositiveIntegerField(
                        default=3600,
                        verbose_name="Максимальная длительность видео (сек)",
                    ),
                ),
                (
                    "allowed_video_formats",
                    models.CharField(
                        default="mp4,avi,mov,wmv",
                        max_length=200,
                        verbose_name="Разрешенные форматы видео",
                    ),
                ),
                (
                    "allow_registration",
                    models.BooleanField(
                        default=True, verbose_name="Разрешить регистрацию"
                    ),
                ),
                (
                    "require_email_verification",
                    models.BooleanField(
                        default=False, verbose_name="Требовать подтверждение email"
                    ),
                ),
                (
                    "max_upload_per_day",
                    models.PositiveIntegerField(
                        default=10,
                        verbose_name="Максимум загрузок в день на пользователя",
                    ),
                ),
                (
                    "auto_publish_videos",
                    models.BooleanField(
                        default=False, verbose_name="Автоматически публиковать видео"
                    ),
                ),
                (
                    "require_moderation",
                    models.BooleanField(
                        default=True, verbose_name="Требовать модерацию"
                    ),
                ),
                (
                    "cache_timeout",
                    models.PositiveIntegerField(
                        default=300, verbose_name="Время кэширования (сек)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
            ],
            options={
                "verbose_name": "Основные настройки",
                "verbose_name_plural": "Основные настройки",
            },
        ),
    ]
