# Generated by Django 5.2.6 on 2025-10-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_seosettings_sitesettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="site_description",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="site_keywords",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="add_site_name_to_title",
            field=models.BooleanField(
                default=True,
                verbose_name="Добавлять в тег title страницы название сайта",
            ),
        ),
        migrations.AlterField(
            model_name="seosettings",
            name="meta_description",
            field=models.TextField(blank=True, verbose_name="Meta Description"),
        ),
    ]
