# Generated by Django 5.2.6 on 2025-11-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_sitesettings_site_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
