# Generated by Django 5.0.1 on 2025-11-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_tag_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalizationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rosetta_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Включить управление переводами через /rosetta/",
                        verbose_name="Включить Rosetta (интерфейс переводов)",
                    ),
                ),
                (
                    "enable_user_language_preference",
                    models.BooleanField(
                        default=True,
                        help_text="Показывать переключатель языка и сохранять предпочтения в профиле",
                        verbose_name="Разрешить пользователям выбирать язык",
                    ),
                ),
                (
                    "default_language",
                    models.CharField(
                        choices=[("en", "English"), ("ru", "Russian")],
                        default="en",
                        help_text="Язык, используемый для гостей и новых пользователей",
                        max_length=5,
                        verbose_name="Язык по умолчанию",
                    ),
                ),
                (
                    "auto_detect_user_language",
                    models.BooleanField(
                        default=False,
                        help_text="Устанавливать язык по Accept-Language заголовку браузера",
                        verbose_name="Автоматически определять язык браузера",
                    ),
                ),
                (
                    "enable_fuzzy_translations",
                    models.BooleanField(
                        default=True,
                        help_text="Показывать приблизительные переводы в Rosetta",
                        verbose_name="Разрешить нечеткие переводы",
                    ),
                ),
                (
                    "translation_cache_timeout",
                    models.PositiveIntegerField(
                        default=3600,
                        help_text="Как долго кэшировать переведенные строки",
                        verbose_name="Время кэширования переводов (сек)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
            ],
            options={
                "verbose_name": "Настройки локализации",
                "verbose_name_plural": "Языки и локализация",
            },
        ),
    ]
