# Generated by Django 5.2.8 on 2025-11-26 09:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_localizationsettings"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LocalizationSettings",
        ),
    ]
