# Generated by Django 4.2.7 on 2025-10-05 08:31

from django.db import migrations, models

import apps.core.utils


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="thumbnail",
        ),
        migrations.AddField(
            model_name="video",
            name="preview",
            field=models.FileField(
                blank=True,
                help_text="Short video preview",
                null=True,
                upload_to=apps.core.utils.generate_thumbnail_path,
            ),
        ),
    ]
