# Generated by Django 5.2.7 on 2025-10-05 09:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import apps.videos.models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0002_remove_video_thumbnail_video_preview"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetadataExtractionSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("poster_width", models.PositiveIntegerField(default=250)),
                ("poster_height", models.PositiveIntegerField(default=150)),
                ("poster_format", models.CharField(default="JPEG", max_length=10)),
                (
                    "poster_quality",
                    models.PositiveIntegerField(
                        default=85,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("preview_width", models.PositiveIntegerField(default=250)),
                ("preview_height", models.PositiveIntegerField(default=150)),
                (
                    "preview_duration",
                    models.PositiveIntegerField(
                        default=12, help_text="Duration in seconds"
                    ),
                ),
                (
                    "preview_segment_duration",
                    models.PositiveIntegerField(
                        default=2, help_text="Segment duration in seconds"
                    ),
                ),
                ("preview_format", models.CharField(default="MP4", max_length=10)),
                (
                    "preview_quality",
                    models.PositiveIntegerField(
                        default=85,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Metadata Extraction Settings",
                "verbose_name_plural": "Metadata Extraction Settings",
            },
        ),
        migrations.CreateModel(
            name="VideoEncodingProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "resolution",
                    models.CharField(
                        help_text="e.g., 360p, 720p, 1080p", max_length=20
                    ),
                ),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("bitrate", models.PositiveIntegerField(help_text="Bitrate in kbps")),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Video Encoding Profile",
                "verbose_name_plural": "Video Encoding Profiles",
                "ordering": ["order", "name"],
            },
        ),
        migrations.RemoveField(
            model_name="video",
            name="video_file",
        ),
        migrations.AddField(
            model_name="video",
            name="temp_video_file",
            field=models.FileField(
                blank=True,
                help_text="Temporary file during processing",
                null=True,
                upload_to="videos/tmp/",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="poster",
            field=models.ImageField(blank=True, null=True, upload_to="posters/"),
        ),
        migrations.AlterField(
            model_name="video",
            name="preview",
            field=models.FileField(
                blank=True,
                help_text="Short video preview",
                null=True,
                upload_to="previews/",
            ),
        ),
        migrations.CreateModel(
            name="VideoFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.videos.models.generate_encoded_video_path
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, help_text="File size in bytes"
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=0, help_text="Duration in seconds"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Primary quality for this video"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="videos.videoencodingprofile",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encoded_files",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video File",
                "verbose_name_plural": "Video Files",
                "unique_together": {("video", "profile")},
            },
        ),
    ]
