# Generated by Django 5.2.7 on 2025-10-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0003_metadataextractionsettings_videoencodingprofile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="converted_files",
            field=models.JSONField(
                blank=True, default=list, help_text="Paths to converted video files"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="temp_video_file",
            field=models.FileField(
                blank=True,
                help_text="Video file (converted versions)",
                null=True,
                upload_to="videos/tmp/",
                verbose_name="Video file",
            ),
        ),
    ]
