# Generated by Django 5.2.7 on 2025-10-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0004_video_converted_files_alter_video_temp_video_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
