# Generated by Django 5.2.7 on 2025-10-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0005_alter_video_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
