# Generated by Django 5.2.7 on 2025-10-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0001_initial"),
        ("videos", "0006_alter_video_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="performers",
            field=models.ManyToManyField(
                blank=True,
                related_name="videos",
                through="models.ModelVideo",
                to="models.model",
            ),
        ),
    ]
