# Generated by Django 5.0.1 on 2025-10-31 05:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_sitesettings_site_description_and_more"),
        ("models", "0001_initial"),
        ("videos", "0008_watchlater"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["created_at"], name="videos_vide_created_f7522a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["category", "is_published"],
                name="videos_vide_categor_c54765_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(fields=["slug"], name="videos_vide_slug_92e2bf_idx"),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["is_published", "status", "-created_at"],
                name="videos_vide_is_publ_57b2e1_idx",
            ),
        ),
    ]
