# Generated by Django 5.2.6 on 2025-11-05 13:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0009_video_videos_vide_created_f7522a_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="video",
            name="videos_vide_created_f7522a_idx",
        ),
        migrations.RemoveIndex(
            model_name="video",
            name="videos_vide_categor_c54765_idx",
        ),
        migrations.RemoveIndex(
            model_name="video",
            name="videos_vide_slug_92e2bf_idx",
        ),
        migrations.RemoveIndex(
            model_name="video",
            name="videos_vide_is_publ_57b2e1_idx",
        ),
    ]
