# Generated by Django 5.2.6 on 2025-11-06 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_tag_slug"),
        ("models", "0001_initial"),
        ("videos", "0010_remove_video_videos_vide_created_f7522a_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="video",
            name="videos_vide_status_9a742e_idx",
        ),
        migrations.RemoveIndex(
            model_name="video",
            name="videos_vide_user_id_0fd0d8_idx",
        ),
        migrations.RemoveField(
            model_name="video",
            name="file_size",
        ),
        migrations.RemoveField(
            model_name="video",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="video",
            name="likes_count",
        ),
        migrations.RemoveField(
            model_name="video",
            name="user",
        ),
        migrations.AddField(
            model_name="video",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Пользователь, который загрузил видео",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_videos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="performers",
            field=models.ManyToManyField(
                blank=True,
                related_name="videos",
                through="models.ModelVideo",
                to="models.model",
                verbose_name="Модели",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="poster",
            field=models.ImageField(
                blank=True,
                help_text="Poster image (250x150px from middle of video)",
                null=True,
                upload_to="posters/",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="preview",
            field=models.FileField(
                blank=True,
                help_text="Short video preview (12 seconds, 6 segments)",
                null=True,
                upload_to="previews/",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="temp_video_file",
            field=models.FileField(
                blank=True,
                help_text="Временный файл видео до обработки",
                null=True,
                upload_to="videos/tmp/",
                verbose_name="Video file",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="views_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Просмотры"),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["status", "created_at"], name="videos_vide_status_e696e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["created_by", "created_at"],
                name="videos_vide_created_b4eda1_idx",
            ),
        ),
    ]
