# Generated by Django 5.2.6 on 2025-11-06 19:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0011_refactor_video_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="comments_count",
        ),
        migrations.RemoveField(
            model_name="video",
            name="dislikes_count",
        ),
        migrations.RemoveField(
            model_name="video",
            name="is_premium",
        ),
    ]
