# Generated by Django 5.2.6 on 2025-11-08 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0013_rating"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="rating",
            name="unique_video_user_rating",
        ),
        migrations.RemoveConstraint(
            model_name="rating",
            name="unique_video_ip_rating",
        ),
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(
                fields=["video", "user"], name="videos_rati_video_i_2c05a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(
                fields=["video", "ip_address"], name="videos_rati_video_i_6f5d70_idx"
            ),
        ),
    ]
