# Generated by Django 5.0.1 on 2025-11-19 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_tag_slug"),
        ("models", "0001_initial"),
        ("videos", "0014_remove_rating_unique_video_user_rating_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="video",
            name="videos_vide_views_c_fd631e_idx",
        ),
        migrations.RemoveIndex(
            model_name="video",
            name="videos_vide_created_b4eda1_idx",
        ),
        migrations.AddField(
            model_name="video",
            name="comments_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Комментарии"),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["status", "is_featured", "created_at"],
                name="videos_vide_status_734a28_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["created_by", "status", "created_at"],
                name="videos_vide_created_e3b594_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["category", "status", "created_at"],
                name="videos_vide_categor_76ecf6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["views_count", "created_at"],
                name="videos_vide_views_c_5194a9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["-views_count", "-created_at"],
                name="videos_vide_views_c_7b8c0f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(fields=["title"], name="videos_vide_title_8a2e81_idx"),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(fields=["slug"], name="videos_vide_slug_92e2bf_idx"),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["status", "category", "views_count"],
                name="videos_vide_status_bb64d5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["status", "is_featured"], name="videos_vide_status_599962_idx"
            ),
        ),
    ]
