# Generated by Django 5.0.1 on 2025-11-19 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0015_remove_video_videos_vide_views_c_fd631e_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "privacy",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("unlisted", "Unlisted"),
                            ("private", "Private"),
                        ],
                        default="public",
                        max_length=10,
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="playlists/"),
                ),
                (
                    "auto_thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="playlists/auto/"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Playlist",
                "verbose_name_plural": "Playlists",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlaylistFollow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to="videos.playlist",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followed_playlists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Playlist Follow",
                "verbose_name_plural": "Playlist Follows",
            },
        ),
        migrations.CreateModel(
            name="PlaylistLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="videos.playlist",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlist_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Playlist Like",
                "verbose_name_plural": "Playlist Likes",
            },
        ),
        migrations.CreateModel(
            name="PlaylistVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlist_videos",
                        to="videos.playlist",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_playlists",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "verbose_name": "Playlist Video",
                "verbose_name_plural": "Playlist Videos",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "verbose_name": "Favorite",
                "verbose_name_plural": "Favorites",
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="videos_favo_user_id_15bdbb_idx",
                    ),
                    models.Index(
                        fields=["video", "created_at"],
                        name="videos_favo_video_i_12ab50_idx",
                    ),
                ],
                "unique_together": {("user", "video")},
            },
        ),
        migrations.AddIndex(
            model_name="playlist",
            index=models.Index(
                fields=["user", "privacy", "created_at"],
                name="videos_play_user_id_f871af_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="playlist",
            index=models.Index(
                fields=["privacy", "created_at"], name="videos_play_privacy_31594c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="playlistfollow",
            unique_together={("user", "playlist")},
        ),
        migrations.AlterUniqueTogether(
            name="playlistlike",
            unique_together={("user", "playlist")},
        ),
        migrations.AddIndex(
            model_name="playlistvideo",
            index=models.Index(
                fields=["playlist", "order"], name="videos_play_playlis_b414b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playlistvideo",
            index=models.Index(fields=["video"], name="videos_play_video_i_9e9075_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="playlistvideo",
            unique_together={("playlist", "video")},
        ),
    ]
