# Generated by Django 5.0.1 on 2025-11-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0016_playlist_playlistfollow_playlistlike_playlistvideo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="comments_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Comments"),
        ),
        migrations.AlterField(
            model_name="video",
            name="processing_error",
            field=models.TextField(blank=True, verbose_name="Processing Error"),
        ),
        migrations.AlterField(
            model_name="video",
            name="processing_progress",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Processing Progress"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="views_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Views"),
        ),
    ]
