# Generated by Django 5.2.8 on 2025-11-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0017_alter_video_comments_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="comments_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Комментарии"),
        ),
        migrations.AlterField(
            model_name="video",
            name="processing_error",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="processing_progress",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="video",
            name="views_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Просмотры"),
        ),
    ]
