# Generated by Django 5.2.8 on 2025-11-26 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0018_improve_video_processing"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoStream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stream_type",
                    models.CharField(
                        choices=[
                            ("hls", "HLS (HTTP Live Streaming)"),
                            ("dash", "DASH (Dynamic Adaptive Streaming)"),
                        ],
                        help_text="Type of streaming protocol",
                        max_length=10,
                    ),
                ),
                (
                    "manifest_path",
                    models.CharField(
                        help_text="Path to manifest file (playlist.m3u8 for HLS or manifest.mpd for DASH)",
                        max_length=500,
                    ),
                ),
                (
                    "segment_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of segments in the stream"
                    ),
                ),
                (
                    "total_size",
                    models.PositiveIntegerField(
                        default=0, help_text="Total size of all segments in bytes"
                    ),
                ),
                (
                    "is_ready",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the stream is ready for playback",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        help_text="Quality profile for this stream",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="videos.videoencodingprofile",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streams",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Stream",
                "verbose_name_plural": "Video Streams",
                "indexes": [
                    models.Index(
                        fields=["video", "stream_type"],
                        name="videos_vide_video_i_7c5e53_idx",
                    ),
                    models.Index(
                        fields=["video", "is_ready"],
                        name="videos_vide_video_i_34b757_idx",
                    ),
                ],
                "unique_together": {("video", "stream_type", "profile")},
            },
        ),
    ]
