# Generated by Django 5.2.8 on 2025-11-26 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0019_videostream"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for the alert rule",
                        max_length=100,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("queue_size", "Queue Size"),
                            ("error_rate", "Error Rate"),
                            ("ffmpeg_unavailable", "FFmpeg Unavailable"),
                            ("disk_space", "Disk Space Low"),
                            ("processing_time", "Processing Time High"),
                        ],
                        help_text="Type of condition to monitor",
                        max_length=20,
                    ),
                ),
                (
                    "threshold_value",
                    models.FloatField(
                        help_text="Threshold value that triggers the alert"
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        default="warning",
                        max_length=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this alert rule is active"
                    ),
                ),
                (
                    "check_interval_minutes",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="How often to check this condition (in minutes)",
                    ),
                ),
                (
                    "cooldown_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Minimum time between alerts of the same type",
                    ),
                ),
                (
                    "send_email",
                    models.BooleanField(
                        default=True, help_text="Send email notifications"
                    ),
                ),
                (
                    "email_recipients",
                    models.TextField(
                        blank=True, help_text="Comma-separated list of email addresses"
                    ),
                ),
                (
                    "webhook_url",
                    models.URLField(
                        blank=True,
                        help_text="Webhook URL for notifications (Slack, Discord, etc.)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alert Rule",
                "verbose_name_plural": "Alert Rules",
                "unique_together": {("alert_type", "name")},
            },
        ),
        migrations.CreateModel(
            name="SystemMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("queue_length", "Queue Length"),
                            ("active_tasks", "Active Tasks"),
                            ("error_count", "Error Count"),
                            ("processing_time_avg", "Average Processing Time"),
                            ("disk_usage", "Disk Usage"),
                            ("ffmpeg_status", "FFmpeg Status"),
                        ],
                        max_length=30,
                    ),
                ),
                ("value", models.FloatField(help_text="Metric value")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional metric data"
                    ),
                ),
            ],
            options={
                "verbose_name": "System Metric",
                "verbose_name_plural": "System Metrics",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["metric_type", "created_at"],
                        name="videos_syst_metric__32f369_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("resolved", "Resolved"),
                            ("acknowledged", "Acknowledged"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("message", models.TextField(help_text="Alert message with details")),
                (
                    "current_value",
                    models.FloatField(
                        blank=True,
                        help_text="Current value that triggered the alert",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional alert metadata"
                    ),
                ),
                ("email_sent", models.BooleanField(default=False)),
                ("webhook_sent", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledged_by",
                    models.CharField(
                        blank=True,
                        help_text="Who acknowledged the alert",
                        max_length=100,
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="videos.alertrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alert",
                "verbose_name_plural": "Alerts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="videos_aler_status_efb1ef_idx",
                    ),
                    models.Index(
                        fields=["rule", "status"], name="videos_aler_rule_id_9f117d_idx"
                    ),
                ],
            },
        ),
    ]
