# Generated by Django 5.0.1 on 2025-10-31 05:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0002_initial"),
        ("videos", "0008_watchlater"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["video", "-created_at"], name="comments_co_video_i_659d5b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["video", "is_pinned", "-created_at"],
                name="comments_co_video_i_650111_idx",
            ),
        ),
    ]
