# Generated by Django 5.2.6 on 2025-11-05 13:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0003_comment_comments_co_video_i_659d5b_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="comment",
            name="comments_co_video_i_659d5b_idx",
        ),
        migrations.RemoveIndex(
            model_name="comment",
            name="comments_co_video_i_650111_idx",
        ),
    ]
