# Generated by Django 5.2.6 on 2025-11-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_subscription_users_subsc_subscri_d96129_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="subscription",
            name="users_subsc_subscri_d96129_idx",
        ),
        migrations.RemoveIndex(
            model_name="subscription",
            name="users_subsc_channel_87da3f_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="users_user_email_6f2530_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="users_user_usernam_65d164_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="users_user_created_cf865c_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="users_user_is_veri_9ce429_idx",
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True,
                choices=[
                    ("US", "United States"),
                    ("GB", "United Kingdom"),
                    ("CA", "Canada"),
                    ("AU", "Australia"),
                    ("DE", "Germany"),
                    ("FR", "France"),
                    ("IT", "Italy"),
                    ("ES", "Spain"),
                    ("NL", "Netherlands"),
                    ("SE", "Sweden"),
                    ("NO", "Norway"),
                    ("DK", "Denmark"),
                    ("FI", "Finland"),
                    ("PL", "Poland"),
                    ("CZ", "Czech Republic"),
                    ("RU", "Russia"),
                    ("UA", "Ukraine"),
                    ("BY", "Belarus"),
                    ("KZ", "Kazakhstan"),
                    ("JP", "Japan"),
                    ("KR", "South Korea"),
                    ("CN", "China"),
                    ("IN", "India"),
                    ("BR", "Brazil"),
                    ("MX", "Mexico"),
                    ("AR", "Argentina"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("other", "Other"),
                    ("prefer_not_to_say", "Prefer not to say"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="orientation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("straight", "Straight"),
                    ("gay", "Gay"),
                    ("lesbian", "Lesbian"),
                    ("bisexual", "Bisexual"),
                    ("pansexual", "Pansexual"),
                    ("other", "Other"),
                    ("prefer_not_to_say", "Prefer not to say"),
                ],
                max_length=20,
            ),
        ),
    ]
