# Generated by Django 5.2.6 on 2025-11-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_notification_friendship"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="education",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Образование"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single"),
                    ("married", "Married"),
                    ("divorced", "Divorced"),
                    ("widowed", "Widowed"),
                    ("separated", "Separated"),
                    ("in_relationship", "In a relationship"),
                    ("prefer_not_to_say", "Prefer not to say"),
                ],
                max_length=20,
                verbose_name="Семейное положение",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, max_length=500, verbose_name="Обо мне"),
        ),
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True,
                choices=[
                    ("US", "United States"),
                    ("GB", "United Kingdom"),
                    ("CA", "Canada"),
                    ("AU", "Australia"),
                    ("DE", "Germany"),
                    ("FR", "France"),
                    ("IT", "Italy"),
                    ("ES", "Spain"),
                    ("NL", "Netherlands"),
                    ("SE", "Sweden"),
                    ("NO", "Norway"),
                    ("DK", "Denmark"),
                    ("FI", "Finland"),
                    ("PL", "Poland"),
                    ("CZ", "Czech Republic"),
                    ("RU", "Russia"),
                    ("UA", "Ukraine"),
                    ("BY", "Belarus"),
                    ("KZ", "Kazakhstan"),
                    ("JP", "Japan"),
                    ("KR", "South Korea"),
                    ("CN", "China"),
                    ("IN", "India"),
                    ("BR", "Brazil"),
                    ("MX", "Mexico"),
                    ("AR", "Argentina"),
                    ("other", "Other"),
                ],
                max_length=50,
                verbose_name="Страна",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("other", "Other"),
                    ("prefer_not_to_say", "Prefer not to say"),
                ],
                max_length=20,
                verbose_name="Пол",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="location",
            field=models.CharField(blank=True, max_length=100, verbose_name="Город"),
        ),
        migrations.AlterField(
            model_name="user",
            name="orientation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("straight", "Straight"),
                    ("gay", "Gay"),
                    ("lesbian", "Lesbian"),
                    ("bisexual", "Bisexual"),
                    ("pansexual", "Pansexual"),
                    ("other", "Other"),
                    ("prefer_not_to_say", "Prefer not to say"),
                ],
                max_length=20,
                verbose_name="Сексуальная ориентация",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="website",
            field=models.URLField(blank=True, verbose_name="Веб-сайт"),
        ),
    ]
