# Generated by Django 5.0.1 on 2025-11-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_education_user_marital_status_alter_user_bio_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AddField(
            model_name="userprofile",
            name="country",
            field=models.CharField(blank=True, max_length=100, verbose_name="Страна"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="show_favorites_publicly",
            field=models.BooleanField(
                default=False, verbose_name="Показывать избранные публично"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="show_friends_publicly",
            field=models.BooleanField(
                default=True, verbose_name="Показывать друзей публично"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="show_playlists_publicly",
            field=models.BooleanField(
                default=True, verbose_name="Показывать плейлисты публично"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="show_subscriptions_publicly",
            field=models.BooleanField(
                default=False, verbose_name="Показывать подписки публично"
            ),
        ),
    ]
