# Generated by Django 5.0.1 on 2025-11-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_user_managers_userprofile_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_login_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="registration_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, max_length=500, verbose_name="Bio"),
        ),
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Birth Date"),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True,
                choices=[
                    ("US", "United States"),
                    ("GB", "United Kingdom"),
                    ("CA", "Canada"),
                    ("AU", "Australia"),
                    ("DE", "Germany"),
                    ("FR", "France"),
                    ("IT", "Italy"),
                    ("ES", "Spain"),
                    ("NL", "Netherlands"),
                    ("SE", "Sweden"),
                    ("NO", "Norway"),
                    ("DK", "Denmark"),
                    ("FI", "Finland"),
                    ("PL", "Poland"),
                    ("CZ", "Czech Republic"),
                    ("RU", "Russia"),
                    ("UA", "Ukraine"),
                    ("BY", "Belarus"),
                    ("KZ", "Kazakhstan"),
                    ("JP", "Japan"),
                    ("KR", "South Korea"),
                    ("CN", "China"),
                    ("IN", "India"),
                    ("BR", "Brazil"),
                    ("MX", "Mexico"),
                    ("AR", "Argentina"),
                    ("other", "Other"),
                ],
                max_length=50,
                verbose_name="Country",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="education",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Education"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("other", "Other"),
                    ("prefer_not_to_say", "Prefer not to say"),
                ],
                max_length=20,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="location",
            field=models.CharField(blank=True, max_length=100, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="user",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single"),
                    ("married", "Married"),
                    ("divorced", "Divorced"),
                    ("widowed", "Widowed"),
                    ("separated", "Separated"),
                    ("in_relationship", "In a relationship"),
                    ("prefer_not_to_say", "Prefer not to say"),
                ],
                max_length=20,
                verbose_name="Marital Status",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="orientation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("straight", "Straight"),
                    ("gay", "Gay"),
                    ("lesbian", "Lesbian"),
                    ("bisexual", "Bisexual"),
                    ("pansexual", "Pansexual"),
                    ("other", "Other"),
                    ("prefer_not_to_say", "Prefer not to say"),
                ],
                max_length=20,
                verbose_name="Sexual Orientation",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="website",
            field=models.URLField(blank=True, verbose_name="Website"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="language",
            field=models.CharField(default="en", max_length=5),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="show_favorites_publicly",
            field=models.BooleanField(
                default=False, verbose_name="Show favorites publicly"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="show_subscriptions_publicly",
            field=models.BooleanField(
                default=False, verbose_name="Show subscriptions publicly"
            ),
        ),
    ]
