# Generated by Django 5.2.8 on 2025-11-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_remove_user_last_login_ip_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="show_playlists_publicly",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="show_subscriptions_publicly",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="show_videos_publicly",
            field=models.BooleanField(
                default=True, verbose_name="Show videos publicly"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="show_watch_later_publicly",
            field=models.BooleanField(
                default=False, verbose_name="Show watch later publicly"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="show_favorites_publicly",
            field=models.BooleanField(
                default=False, verbose_name="Show favorites publicly"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="show_friends_publicly",
            field=models.BooleanField(
                default=True, verbose_name="Show friends publicly"
            ),
        ),
    ]
