# Generated by Django 5.2.8 on 2025-11-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_add_privacy_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_premium",
            field=models.BooleanField(
                default=False,
                help_text="Premium пользователи получают приоритет в обработке видео",
                verbose_name="Premium пользователь",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="processing_priority",
            field=models.IntegerField(
                default=5,
                help_text="Чем выше число, тем выше приоритет (0-10)",
                verbose_name="Приоритет обработки",
            ),
        ),
    ]
