# Generated by Django 5.2.7 on 2025-10-07 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdPlacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Слаг"),
                ),
                (
                    "placement_type",
                    models.CharField(
                        choices=[
                            ("banner", "Баннер"),
                            ("sidebar", "Боковая панель"),
                            ("header", "Заголовок"),
                            ("footer", "Подвал"),
                            ("popup", "Всплывающее окно"),
                            ("video_overlay", "Наложение на видео"),
                            ("in_content", "Внутри контента"),
                        ],
                        max_length=20,
                        verbose_name="Тип размещения",
                    ),
                ),
                ("width", models.PositiveIntegerField(verbose_name="Ширина (px)")),
                ("height", models.PositiveIntegerField(verbose_name="Высота (px)")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Место размещения",
                "verbose_name_plural": "Места размещения",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AdCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название кампании"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Бюджет",
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="Дата начала")),
                ("end_date", models.DateTimeField(verbose_name="Дата окончания")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("active", "Активная"),
                            ("paused", "Приостановлена"),
                            ("completed", "Завершена"),
                            ("cancelled", "Отменена"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "target_impressions",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Целевые показы"
                    ),
                ),
                (
                    "target_clicks",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Целевые клики"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "advertiser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_campaigns",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Рекламодатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рекламная кампания",
                "verbose_name_plural": "Рекламные кампании",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название баннера"),
                ),
                (
                    "banner_type",
                    models.CharField(
                        choices=[
                            ("image", "Изображение"),
                            ("video", "Видео"),
                            ("html", "HTML"),
                            ("text", "Текст"),
                        ],
                        max_length=20,
                        verbose_name="Тип баннера",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="ads/images/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="ads/videos/",
                        verbose_name="Видео",
                    ),
                ),
                (
                    "html_content",
                    models.TextField(blank=True, verbose_name="HTML контент"),
                ),
                (
                    "text_content",
                    models.TextField(blank=True, verbose_name="Текстовый контент"),
                ),
                ("target_url", models.URLField(verbose_name="Целевая ссылка")),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Альтернативный текст"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(default=0, verbose_name="Приоритет"),
                ),
                (
                    "weight",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Вес (для ротации)"
                    ),
                ),
                (
                    "impressions_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество показов"
                    ),
                ),
                (
                    "clicks_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество кликов"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banners",
                        to="ads.adcampaign",
                        verbose_name="Кампания",
                    ),
                ),
                (
                    "placement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banners",
                        to="ads.adplacement",
                        verbose_name="Место размещения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рекламный баннер",
                "verbose_name_plural": "Рекламные баннеры",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP адрес")),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                ("referer", models.URLField(blank=True, verbose_name="Реферер")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "banner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clicks",
                        to="ads.adbanner",
                        verbose_name="Баннер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Клик по рекламе",
                "verbose_name_plural": "Клики по рекламе",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdImpression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP адрес")),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                ("referer", models.URLField(blank=True, verbose_name="Реферер")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "banner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impressions",
                        to="ads.adbanner",
                        verbose_name="Баннер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Показ рекламы",
                "verbose_name_plural": "Показы рекламы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название зоны"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Слаг"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "placements",
                    models.ManyToManyField(
                        related_name="zones",
                        to="ads.adplacement",
                        verbose_name="Места размещения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рекламная зона",
                "verbose_name_plural": "Рекламные зоны",
                "ordering": ["name"],
            },
        ),
    ]
